"""Translations of the HTML report's interface, keyed by the Portuguese text.

Each entry is (Portuguese, English, Spanish, French, German). The Portuguese
is exactly the string the code passes to `t`, placeholders included, and every
translation carries the same placeholders.

Abbreviations of Portuguese bodies and terms (DGS, RCM, DPOC...) are kept as
they are in every language: they appear that way in the cases, which stay in
Portuguese, and the glossary explains them in the reader's language.
"""

from __future__ import annotations

_SAME = (
    "DGS", "Infarmed", "RCM", "APMGF", "EMA", "FDA", "ESC", "ADA", "NICE", "SNS", "PNV",
    "DPOC", "TFG", "AVC", "HbA1c", "INR", "IECA", "ECA", "ARA II", "DOAC", "TSN", "SGLT2",
    "CYP3A4", "MAPA", "AMPA", "TA", "IM", "IV", "SCORE2", "SCORE", "SHA-256", "Ollama",
    "tokens_max", "COVID-19", "Helicobacter pylori",
    "{a} de {n}",
)

_ROWS: tuple[tuple[str, str, str, str, str], ...] = (
    # ---- page frame
    # ---- the pages of the report (navigation, headings, the strip every page carries)
    ("Início", "Start", "Inicio", "Accueil", "Start"),
    ("Fontes", "Sources", "Fuentes", "Sources", "Quellen"),
    ("Resultados", "Results", "Resultados", "Résultats", "Ergebnisse"),
    ("Casos", "Cases", "Casos", "Cas", "Fälle"),
    ("Conclusões", "Conclusions", "Conclusiones", "Conclusions", "Schlussfolgerungen"),
    ("Método e detalhes técnicos", "Method and technical details", "Método y detalles técnicos",
     "Méthode et détails techniques", "Methode und technische Details"),
    ("Veredictos: triagem automática do corretor, sem validação clínica.",
     "Verdicts: automatic triage by the grader, not clinically validated.",
     "Veredictos: cribado automático del corrector, sin validación clínica.",
     "Verdicts : tri automatique par le correcteur, sans validation clinique.",
     "Urteile: automatische Vorauswahl durch den Bewerter, ohne klinische Validierung."),
    ("Fontes por confirmar.", "Sources to be confirmed.", "Fuentes por confirmar.", "Sources à confirmer.",
     "Quellen noch zu bestätigen."),
    ("Todas as fontes destes casos foram confirmadas por uma pessoa.",
     "Every source of these cases has been confirmed by a person.",
     "Todas las fuentes de estos casos han sido confirmadas por una persona.",
     "Toutes les sources de ces cas ont été confirmées par une personne.",
     "Alle Quellen dieser Fälle wurden von einer Person bestätigt."),
    ("Tradução automática, não revista por um falante nativo; em caso de dúvida vale o português.",
     "Machine translation, not reviewed by a native speaker; if in doubt, the Portuguese prevails.",
     "Traducción automática, no revisada por un hablante nativo; en caso de duda, vale el portugués.",
     "Traduction automatique, non relue par un locuteur natif ; en cas de doute, le portugais fait foi.",
     "Maschinelle Übersetzung, nicht von einer Muttersprachlerin oder einem Muttersprachler geprüft; im Zweifel gilt das Portugiesische."),
    ("Relatório do Aferidor", "Aferidor report", "Informe del Aferidor", "Rapport de l'Aferidor", "Aferidor-Bericht"),
    ("Aferidor · banco de ensaio clínico", "Aferidor · clinical test bench", "Aferidor · banco de pruebas clínico", "Aferidor · banc d'essai clinique", "Aferidor · klinischer Prüfstand"),
    ("Respostas clínicas de modelos de linguagem, medidas contra casos de referência com fonte pública.",
     "Clinical answers from language models, measured against reference cases with a public source.",
     "Respuestas clínicas de modelos de lenguaje, medidas frente a casos de referencia con fuente pública.",
     "Réponses cliniques de modèles de langage, mesurées par rapport à des cas de référence à source publique.",
     "Klinische Antworten von Sprachmodellen, gemessen an Referenzfällen mit öffentlicher Quelle."),
    ("Relatório escrito em {data}.", "Report written on {data}.", "Informe redactado el {data}.", "Rapport rédigé le {data}.", "Bericht erstellt am {data}."),
    ("Código, método e casos no GitHub", "Code, method and cases on GitHub", "Código, método y casos en GitHub",
     "Code, méthode et cas sur GitHub", "Code, Methode und Fälle auf GitHub"),
    ("Limiar de referência: nenhum caso com {falha}, o limiar usado nos protocolos do projeto. Não é um protocolo escrito antes do ensaio.",
     "Reference threshold: no case with a {falha}, the threshold used in the project's protocols. It is not a protocol written before the trial.",
     "Umbral de referencia: ningún caso con {falha}, el umbral usado en los protocolos del proyecto. No es un protocolo escrito antes del ensayo.",
     "Seuil de référence : aucun cas avec une {falha}, le seuil utilisé dans les protocoles du projet. Ce n'est pas un protocole rédigé avant l'essai.",
     "Referenzschwelle: kein Fall, in dem ein {falha} auftritt. Das ist die Schwelle, die in den Protokollen des Projekts verwendet wird; es ist kein vor dem Versuch verfasstes Protokoll."),
    ("Modelos que cumprem o limiar de referência: {k} de {n}.",
     "Models that meet the reference threshold: {k} of {n}.",
     "Modelos que cumplen el umbral de referencia: {k} de {n}.",
     "Modèles qui respectent le seuil de référence : {k} sur {n}.",
     "Modelle, die die Referenzschwelle erfüllen: {k} von {n}."),
    ("Melhor resultado: {a} de {b} casos com {falha}.",
     "Best result: {a} of {b} cases with a {falha}.",
     "Mejor resultado: {a} de {b} casos con {falha}.",
     "Meilleur résultat : {a} cas sur {b} avec une {falha}.",
     "Bestes Ergebnis: {a} von {b} Fällen, in denen ein {falha} auftritt."),
    ("fontes por confirmar", "sources to be confirmed", "fuentes por confirmar", "sources à confirmer",
     "Quellen noch zu bestätigen"),
    ("cumpre o limiar de referência", "meets the reference threshold", "cumple el umbral de referencia",
     "respecte le seuil de référence", "erfüllt die Referenzschwelle"),
    ("não cumpre o limiar de referência", "does not meet the reference threshold", "no cumple el umbral de referencia",
     "ne respecte pas le seuil de référence", "erfüllt die Referenzschwelle nicht"),
    ("Resumo do relatório: modelos comparados pelo número de casos com falha crítica",
     "Report summary: models compared by number of cases with a critical failure",
     "Resumen del informe: modelos comparados por número de casos con fallo crítico",
     "Résumé du rapport : modèles comparés selon le nombre de cas avec une défaillance critique",
     "Berichtszusammenfassung: Modelle verglichen nach der Anzahl der Fälle mit kritischem Fehler"),
    ("Tema", "Theme", "Tema", "Thème", "Design"),
    ("Claro", "Light", "Claro", "Clair", "Hell"),
    ("Escuro", "Dark", "Oscuro", "Sombre", "Dunkel"),
    ("Língua", "Language", "Idioma", "Langue", "Sprache"),
    ("Secções", "Sections", "Secciones", "Sections", "Abschnitte"),
    ("Resumo", "Summary", "Resumen", "Synthèse", "Zusammenfassung"),
    ("Critério de aprovação", "Approval criterion", "Criterio de aprobación", "Critère d'approbation", "Freigabekriterium"),
    ("Erros mais graves", "Most serious errors", "Errores más graves", "Erreurs les plus graves", "Schwerwiegendste Fehler"),
    ("Por área clínica", "By clinical area", "Por área clínica", "Par domaine clinique", "Nach klinischem Bereich"),
    ("Resultados por caso", "Results by case", "Resultados por caso", "Résultats par cas", "Ergebnisse je Fall"),
    ("Casos com falha", "Cases with failures", "Casos con fallos", "Cas en échec", "Fälle mit Fehlern"),
    ("Mais indicadores", "More indicators", "Más indicadores", "Autres indicateurs", "Weitere Indikatoren"),
    ("Detalhes técnicos", "Technical details", "Detalles técnicos", "Détails techniques", "Technische Details"),
    ("Não há veredictos para relatar.", "There are no verdicts to report.", "No hay veredictos que informar.", "Aucun verdict à rapporter.", "Keine Urteile zu berichten."),
    ("Este documento mede um sistema, não um doente. Não aconselha, não trata e não substitui julgamento clínico.",
     "This document measures a system, not a patient. It does not advise, does not treat and does not replace clinical judgement.",
     "Este documento mide un sistema, no a un paciente. No aconseja, no trata y no sustituye el juicio clínico.",
     "Ce document mesure un système, pas un patient. Il ne conseille pas, ne traite pas et ne remplace pas le jugement clinique.",
     "Dieses Dokument misst ein System, keinen Patienten. Es berät nicht, behandelt nicht und ersetzt kein klinisches Urteil."),

    # ---- opening
    ("Sobre este relatório", "About this report", "Sobre este informe", "À propos de ce rapport", "Über diesen Bericht"),
    ("O <strong>Aferidor</strong> avalia a exatidão de modelos de linguagem em perguntas clínicas em português europeu e classifica os erros pelo risco clínico.",
     "<strong>Aferidor</strong> assesses the accuracy of language models on clinical questions in European Portuguese and classifies errors by clinical risk.",
     "<strong>Aferidor</strong> evalúa la exactitud de modelos de lenguaje en preguntas clínicas en portugués europeo y clasifica los errores según el riesgo clínico.",
     "<strong>Aferidor</strong> évalue l'exactitude des modèles de langage sur des questions cliniques en portugais européen et classe les erreurs selon le risque clinique.",
     "<strong>Aferidor</strong> bewertet die Genauigkeit von Sprachmodellen bei klinischen Fragen auf europäischem Portugiesisch und ordnet Fehler nach klinischem Risiko ein."),
    ("Os veredictos são a triagem automática do corretor; a validação por um especialista faz-se à parte, numa folha cega ({comando}).",
     "The verdicts are the grader's automatic triage; validation by a specialist is done separately, on a blind sheet ({comando}).",
     "Los veredictos son el cribado automático del corrector; la validación por un especialista se hace aparte, en una hoja ciega ({comando}).",
     "Les verdicts constituent le tri automatique du correcteur ; la validation par un spécialiste se fait à part, sur une feuille en aveugle ({comando}).",
     "Die Urteile sind die automatische Vorauswahl des Bewerters; die Validierung durch eine Fachperson erfolgt separat, auf einem verblindeten Bogen ({comando})."),
    ("caso clínico", "clinical case", "caso clínico", "cas clinique", "klinischer Fall"),
    ("casos clínicos", "clinical cases", "casos clínicos", "cas cliniques", "klinische Fälle"),
    ("modelo", "model", "modelo", "modèle", "Modell"),
    ("modelos", "models", "modelos", "modèles", "Modelle"),
    ("amostra por caso", "sample per case", "muestra por caso", "échantillon par cas", "Stichprobe pro Fall"),
    ("amostras por caso", "samples per case", "muestras por caso", "échantillons par cas", "Stichproben pro Fall"),
    ("Como interpretar este relatório", "How to read this report", "Cómo interpretar este informe", "Comment lire ce rapport", "So lesen Sie diesen Bericht"),
    ("Cada pergunta tem uma resposta de referência com fonte pública (normas da {dgs}, {infarmed}, diretrizes europeias) e critérios de aceitação definidos antes do ensaio. Cada pergunta é colocada várias vezes a cada modelo, uma vez que as respostas variam; cada resposta constitui uma {amostra}. A correção é automática e determinista. Como a média de respostas corretas oculta os erros relevantes, o relatório apresenta primeiro as falhas críticas.",
     "Each question has a reference answer with a public source ({dgs} guidelines, {infarmed}, European guidelines) and acceptance criteria defined before the test. Each question is put to each model several times, because answers vary; each answer is a {amostra}. Grading is automatic and deterministic. Because the average of correct answers hides the errors that matter, the report shows critical failures first.",
     "Cada pregunta tiene una respuesta de referencia con fuente pública (normas de la {dgs}, {infarmed}, guías europeas) y criterios de aceptación definidos antes de la prueba. Cada pregunta se formula varias veces a cada modelo, ya que las respuestas varían; cada respuesta es una {amostra}. La corrección es automática y determinista. Como la media de respuestas correctas oculta los errores relevantes, el informe presenta primero los fallos críticos.",
     "Chaque question a une réponse de référence à source publique (normes de la {dgs}, {infarmed}, recommandations européennes) et des critères d'acceptation définis avant l'essai. Chaque question est posée plusieurs fois à chaque modèle, car les réponses varient ; chaque réponse constitue un {amostra}. La correction est automatique et déterministe. La moyenne des réponses correctes masquant les erreurs importantes, le rapport présente d'abord les défaillances critiques.",
     "Jede Frage hat eine Referenzantwort mit öffentlicher Quelle (Leitlinien der {dgs}, {infarmed}, europäische Leitlinien) und vor dem Test festgelegte Akzeptanzkriterien. Jede Frage wird jedem Modell mehrmals gestellt, da die Antworten variieren; jede Antwort ist eine {amostra}. Die Bewertung ist automatisch und deterministisch. Da der Durchschnitt richtiger Antworten die relevanten Fehler verdeckt, zeigt der Bericht zuerst die kritischen Fehler."),
    ("<li><strong>O valor em destaque</strong> indica os casos com pelo menos uma {falha}. Na prática clínica é observada uma única resposta; uma falha crítica é suficiente.</li><li><strong>A barra de estados</strong> indica a consistência de cada modelo: casos {sempre}, {parcial} e {nunca}.</li><li><strong>A secção Casos com falha</strong> apresenta, para cada caso, a pergunta, a referência, a resposta do modelo e o critério não cumprido, para que cada veredicto possa ser verificado.</li>",
     "<li><strong>The highlighted number</strong> shows the cases with at least one {falha}. In clinical practice a single answer is seen; one critical failure is enough.</li><li><strong>The status bar</strong> shows each model's consistency: {sempre}, {parcial} and {nunca} cases.</li><li><strong>The Cases with failures section</strong> shows, for each case, the question, the reference, the model's answer and the unmet criterion, so that every verdict can be checked.</li>",
     "<li><strong>La cifra destacada</strong> indica los casos con al menos un {falha}. En la práctica clínica se observa una única respuesta; un fallo crítico es suficiente.</li><li><strong>La barra de estados</strong> indica la consistencia de cada modelo: casos {sempre}, {parcial} y {nunca}.</li><li><strong>La sección Casos con fallos</strong> presenta, para cada caso, la pregunta, la referencia, la respuesta del modelo y el criterio incumplido, para que cada veredicto pueda verificarse.</li>",
     "<li><strong>La valeur mise en évidence</strong> indique les cas présentant au moins une {falha}. En pratique clinique, une seule réponse est observée ; une défaillance critique suffit.</li><li><strong>La barre d'états</strong> indique la cohérence de chaque modèle : cas {sempre}, {parcial} et {nunca}.</li><li><strong>La section Cas en échec</strong> présente, pour chaque cas, la question, la référence, la réponse du modèle et le critère non respecté, afin que chaque verdict puisse être vérifié.</li>",
     "<li><strong>Der hervorgehobene Wert</strong> zeigt die Fälle mit mindestens einem {falha}. In der klinischen Praxis wird nur eine Antwort gesehen; ein kritischer Fehler genügt.</li><li><strong>Die Statusleiste</strong> zeigt die Konsistenz jedes Modells: Fälle {sempre}, {parcial} und {nunca}.</li><li><strong>Der Abschnitt Fälle mit Fehlern</strong> zeigt für jeden Fall die Frage, die Referenz, die Antwort des Modells und das nicht erfüllte Kriterium, damit jedes Urteil überprüft werden kann.</li>"),
    ("sempre corretos", "always correct", "siempre correctos", "toujours corrects", "immer richtig"),
    ("parcialmente corretos", "partially correct", "parcialmente correctos", "partiellement corrects", "teilweise richtig"),
    ("nunca corretos", "never correct", "nunca correctos", "jamais corrects", "nie richtig"),
    ("Método de contagem", "Counting method", "Método de recuento", "Méthode de comptage", "Zählmethode"),
    ("vez", "time", "vez", "fois", "Mal"),
    ("vezes", "times", "veces", "fois", "Mal"),
    ("Cada caso foi colocado {vezes} a cada modelo; cada resposta é uma {amostra}. Na grelha, cada ponto representa uma amostra, pela ordem de execução: {certa} correta, {errada} incorreta, {falta} sem resposta.",
     "Each case was put to each model {vezes}; each answer is a {amostra}. In the grid, each dot is a sample, in the order it was run: {certa} correct, {errada} incorrect, {falta} no answer.",
     "Cada caso se formuló {vezes} a cada modelo; cada respuesta es una {amostra}. En la tabla, cada punto representa una muestra, por orden de ejecución: {certa} correcta, {errada} incorrecta, {falta} sin respuesta.",
     "Chaque cas a été posé {vezes} à chaque modèle ; chaque réponse est un {amostra}. Dans la grille, chaque point représente un échantillon, dans l'ordre d'exécution : {certa} correct, {errada} incorrect, {falta} sans réponse.",
     "Jeder Fall wurde jedem Modell {vezes} gestellt; jede Antwort ist eine {amostra}. In der Tabelle steht jeder Punkt für eine Stichprobe, in Ausführungsreihenfolge: {certa} richtig, {errada} falsch, {falta} keine Antwort."),
    ("todas as amostras corretas", "all samples correct", "todas las muestras correctas", "tous les échantillons corrects", "alle Stichproben richtig"),
    ("algumas amostras corretas", "some samples correct", "algunas muestras correctas", "certains échantillons corrects", "einige Stichproben richtig"),
    ("nenhuma amostra correta", "no sample correct", "ninguna muestra correcta", "aucun échantillon correct", "keine Stichprobe richtig"),
    ("{casos}: veredicto binário por caso. Regra deste relatório: um caso é correto quando {regra}.",
     "{casos}: a yes-or-no verdict per case. Rule in this report: a case is correct when {regra}.",
     "{casos}: veredicto binario por caso. Regla de este informe: un caso es correcto cuando {regra}.",
     "{casos} : verdict binaire par cas. Règle de ce rapport : un cas est correct lorsque {regra}.",
     "{casos}: binäres Urteil je Fall. Regel dieses Berichts: Ein Fall ist richtig, wenn {regra}."),
    ("<strong>Um caso nunca correto não tem necessariamente uma {falha}</strong>, e um caso parcialmente correto pode ter uma. Por esse motivo, as falhas críticas são contadas à parte.",
     "<strong>A never-correct case does not necessarily have a {falha}</strong>, and a partially correct case may have one. Critical failures are therefore counted separately.",
     "<strong>Un caso nunca correcto no tiene necesariamente un {falha}</strong>, y un caso parcialmente correcto puede tener uno. Por ese motivo, los fallos críticos se cuentan aparte.",
     "<strong>Un cas jamais correct ne comporte pas nécessairement de {falha}</strong>, et un cas partiellement correct peut en comporter une. Les défaillances critiques sont donc comptées à part.",
     "<strong>Ein nie richtiger Fall hat nicht unbedingt einen {falha}</strong>, und ein teilweise richtiger Fall kann einen haben. Kritische Fehler werden daher gesondert gezählt."),

    # ---- notices
    ("Língua dos casos.", "Language of the cases.", "Idioma de los casos.", "Langue des cas.", "Sprache der Fälle."),
    ("As perguntas, as respostas de referência e as respostas dos modelos são apresentadas no original, em português europeu: são o objeto da avaliação.",
     "Questions, reference answers and model answers are shown in the original European Portuguese: they are what was assessed.",
     "Las preguntas, las respuestas de referencia y las respuestas de los modelos se presentan en el original, en portugués europeo: son el objeto de la evaluación.",
     "Les questions, les réponses de référence et les réponses des modèles sont présentées dans l'original, en portugais européen : elles constituent l'objet de l'évaluation.",
     "Fragen, Referenzantworten und Modellantworten werden im Original auf europäischem Portugiesisch gezeigt: Sie sind Gegenstand der Bewertung."),
    ("Aviso.", "Notice.", "Aviso.", "Avertissement.", "Hinweis."),
    ("Nem todas as fontes destes casos foram confirmadas por uma pessoa. Até essa confirmação, os resultados medem o modelo contra valores transcritos automaticamente. Ver {ficheiro}.",
     "Not all sources for these cases have been confirmed by a person. Until then, the results measure the model against automatically transcribed values. See {ficheiro}.",
     "No todas las fuentes de estos casos han sido confirmadas por una persona. Hasta esa confirmación, los resultados miden el modelo frente a valores transcritos automáticamente. Véase {ficheiro}.",
     "Toutes les sources de ces cas n'ont pas été confirmées par une personne. Jusqu'à cette confirmation, les résultats mesurent le modèle par rapport à des valeurs transcrites automatiquement. Voir {ficheiro}.",
     "Nicht alle Quellen dieser Fälle wurden von einer Person bestätigt. Bis dahin messen die Ergebnisse das Modell an automatisch übertragenen Werten. Siehe {ficheiro}."),
    ("Casos sem resposta.", "Cases without an answer.", "Casos sin respuesta.", "Cas sans réponse.", "Fälle ohne Antwort."),
    ("Não entram em nenhuma contagem deste relatório.", "They are not included in any count in this report.", "No se incluyen en ningún recuento de este informe.", "Ils ne sont inclus dans aucun décompte de ce rapport.", "Sie gehen in keine Zählung dieses Berichts ein."),
    ("Amostras em falta.", "Missing samples.", "Muestras que faltan.", "Échantillons manquants.", "Fehlende Stichproben."),
    ("Não muda nenhuma contagem abaixo; só nomeia o que já era invisível nelas.",
     "This changes no count below; it only names what was already invisible in them.",
     "No cambia ningún recuento; solo nombra lo que ya era invisible en ellos.",
     "Cela ne modifie aucun décompte ; cela nomme seulement ce qui y était déjà invisible.",
     "Das ändert keine Zählung; es benennt nur, was darin bereits unsichtbar war."),
    ("{caso} ({modelo}, {a} de {n} amostras)", "{caso} ({modelo}, {a} of {n} samples)", "{caso} ({modelo}, {a} de {n} muestras)", "{caso} ({modelo}, {a} sur {n} échantillons)", "{caso} ({modelo}, {a} von {n} Stichproben)"),

    # ---- summary and cards
    ("Contexto.", "Context.", "Contexto.", "Contexte.", "Kontext."),
    ("{nomes} foi executado localmente, num computador portátil, através do Ollama. São modelos abertos de pequena dimensão; os resultados não são extrapoláveis para os modelos comerciais disponibilizados por API.",
     "{nomes} was run locally, on a laptop, through Ollama. These are small open models; the results cannot be extrapolated to the commercial models offered through APIs.",
     "{nomes} se ejecutó localmente, en un portátil, mediante Ollama. Son modelos abiertos de pequeño tamaño; los resultados no son extrapolables a los modelos comerciales ofrecidos por API.",
     "{nomes} a été exécuté localement, sur un ordinateur portable, via Ollama. Il s'agit de petits modèles ouverts ; les résultats ne sont pas extrapolables aux modèles commerciaux proposés par API.",
     "{nomes} wurde lokal auf einem Laptop über Ollama ausgeführt. Es handelt sich um kleine offene Modelle; die Ergebnisse sind nicht auf kommerzielle, per API angebotene Modelle übertragbar."),
    ("{nomes} foram executados localmente, num computador portátil, através do Ollama. São modelos abertos de pequena dimensão; os resultados não são extrapoláveis para os modelos comerciais disponibilizados por API.",
     "{nomes} were run locally, on a laptop, through Ollama. These are small open models; the results cannot be extrapolated to the commercial models offered through APIs.",
     "{nomes} se ejecutaron localmente, en un portátil, mediante Ollama. Son modelos abiertos de pequeño tamaño; los resultados no son extrapolables a los modelos comerciales ofrecidos por API.",
     "{nomes} ont été exécutés localement, sur un ordinateur portable, via Ollama. Il s'agit de petits modèles ouverts ; les résultats ne sont pas extrapolables aux modèles commerciaux proposés par API.",
     "{nomes} wurden lokal auf einem Laptop über Ollama ausgeführt. Es handelt sich um kleine offene Modelle; die Ergebnisse sind nicht auf kommerzielle, per API angebotene Modelle übertragbar."),
    (" e ", " and ", " y ", " et ", " und "),
    ("{a} e {b} tiveram a mesma proporção de casos com falha crítica.",
     "{a} and {b} had the same proportion of cases with a critical failure.",
     "{a} y {b} tuvieron la misma proporción de casos con fallo crítico.",
     "{a} et {b} ont eu la même proportion de cas avec une défaillance critique.",
     "{a} und {b} hatten denselben Anteil an Fällen mit kritischem Fehler."),
    ("{melhor} teve menos casos com falha crítica ({a} de {n}, contra {b} de {m} de {outro}), mas os intervalos de confiança sobrepõem-se: com {n} casos, a diferença pode dever-se ao acaso.",
     "{melhor} had fewer cases with a critical failure ({a} of {n}, against {b} of {m} for {outro}), but the confidence intervals overlap: with {n} cases, the difference may be due to chance.",
     "{melhor} tuvo menos casos con fallo crítico ({a} de {n}, frente a {b} de {m} de {outro}), pero los intervalos de confianza se solapan: con {n} casos, la diferencia puede deberse al azar.",
     "{melhor} a eu moins de cas avec une défaillance critique ({a} sur {n}, contre {b} sur {m} pour {outro}), mais les intervalles de confiance se chevauchent : avec {n} cas, la différence peut être due au hasard.",
     "{melhor} hatte weniger Fälle mit kritischem Fehler ({a} von {n}, gegenüber {b} von {m} bei {outro}), aber die Konfidenzintervalle überlappen sich: Bei {n} Fällen kann der Unterschied zufällig sein."),
    ("{melhor} teve menos casos com falha crítica ({a} de {n}, contra {b} de {m} de {outro}), e os intervalos de confiança não se sobrepõem.",
     "{melhor} had fewer cases with a critical failure ({a} of {n}, against {b} of {m} for {outro}), and the confidence intervals do not overlap.",
     "{melhor} tuvo menos casos con fallo crítico ({a} de {n}, frente a {b} de {m} de {outro}), y los intervalos de confianza no se solapan.",
     "{melhor} a eu moins de cas avec une défaillance critique ({a} sur {n}, contre {b} sur {m} pour {outro}), et les intervalles de confiance ne se chevauchent pas.",
     "{melhor} hatte weniger Fälle mit kritischem Fehler ({a} von {n}, gegenüber {b} von {m} bei {outro}), und die Konfidenzintervalle überlappen sich nicht."),
    ("{melhor} teve menos casos com falha crítica ({a} de {n}, contra {b} de {m} de {outro}). Nos casos em que só um dos dois teve falha crítica ({x} contra {y}), a diferença é estatisticamente significativa (teste de McNemar exato, {p}).",
     "{melhor} had fewer cases with a critical failure ({a} of {n}, against {b} of {m} for {outro}). In the cases where only one of the two had a critical failure ({x} against {y}), the difference is statistically significant (exact McNemar test, {p}).",
     "{melhor} tuvo menos casos con fallo crítico ({a} de {n}, frente a {b} de {m} de {outro}). En los casos en que solo uno de los dos tuvo fallo crítico ({x} frente a {y}), la diferencia es estadísticamente significativa (prueba exacta de McNemar, {p}).",
     "{melhor} a eu moins de cas avec une défaillance critique ({a} sur {n}, contre {b} sur {m} pour {outro}). Dans les cas où un seul des deux a eu une défaillance critique ({x} contre {y}), la différence est statistiquement significative (test exact de McNemar, {p}).",
     "{melhor} hatte weniger Fälle mit kritischem Fehler ({a} von {n}, gegenüber {b} von {m} bei {outro}). In den Fällen, in denen nur eines der beiden einen kritischen Fehler hatte ({x} gegenüber {y}), ist der Unterschied statistisch signifikant (exakter McNemar-Test, {p})."),
    ("{melhor} teve menos casos com falha crítica ({a} de {n}, contra {b} de {m} de {outro}). Nos casos em que só um dos dois teve falha crítica ({x} contra {y}), a diferença pode dever-se ao acaso (teste de McNemar exato, {p}).",
     "{melhor} had fewer cases with a critical failure ({a} of {n}, against {b} of {m} for {outro}). In the cases where only one of the two had a critical failure ({x} against {y}), the difference may be due to chance (exact McNemar test, {p}).",
     "{melhor} tuvo menos casos con fallo crítico ({a} de {n}, frente a {b} de {m} de {outro}). En los casos en que solo uno de los dos tuvo fallo crítico ({x} frente a {y}), la diferencia puede deberse al azar (prueba exacta de McNemar, {p}).",
     "{melhor} a eu moins de cas avec une défaillance critique ({a} sur {n}, contre {b} sur {m} pour {outro}). Dans les cas où un seul des deux a eu une défaillance critique ({x} contre {y}), la différence peut être due au hasard (test exact de McNemar, {p}).",
     "{melhor} hatte weniger Fälle mit kritischem Fehler ({a} von {n}, gegenüber {b} von {m} bei {outro}). In den Fällen, in denen nur eines der beiden einen kritischen Fehler hatte ({x} gegenüber {y}), kann der Unterschied zufällig sein (exakter McNemar-Test, {p})."),
    ("{modelo}: {a} de {n} casos com falha crítica, intervalo de {low} a {high}",
     "{modelo}: {a} of {n} cases with a critical failure, interval {low} to {high}",
     "{modelo}: {a} de {n} casos con fallo crítico, intervalo de {low} a {high}",
     "{modelo} : {a} sur {n} cas avec une défaillance critique, intervalle de {low} à {high}",
     "{modelo}: {a} von {n} Fällen mit kritischem Fehler, Intervall {low} bis {high}"),
    ("Percentagem de casos com falha crítica em alguma amostra. O ponto é o observado; a linha, o intervalo de confiança a 95%.",
     "Percentage of cases with a critical failure in any sample. The dot is the observed value; the line, the 95% confidence interval.",
     "Porcentaje de casos con fallo crítico en alguna muestra. El punto es el valor observado; la línea, el intervalo de confianza del 95 %.",
     "Pourcentage de cas avec une défaillance critique dans au moins un échantillon. Le point est la valeur observée ; la ligne, l'intervalle de confiance à 95 %.",
     "Anteil der Fälle mit kritischem Fehler in mindestens einer Stichprobe. Der Punkt ist der beobachtete Wert, die Linie das 95-%-Konfidenzintervall."),
    ("IC 95% {low} a {high}", "95% CI {low} to {high}", "IC 95 % {low} a {high}", "IC 95 % {low} à {high}", "95-%-KI {low} bis {high}"),
    ("aprovado pelo protocolo", "approved by the protocol", "aprobado por el protocolo", "approuvé par le protocole", "vom Protokoll freigegeben"),
    ("reprovado pelo protocolo", "rejected by the protocol", "rechazado por el protocolo", "refusé par le protocole", "vom Protokoll abgelehnt"),
    ("de {total} casos com {falha} em alguma amostra ({ic})",
     "of {total} cases with a {falha} in any sample ({ic})",
     "de {total} casos con {falha} en alguna muestra ({ic})",
     "sur {total} cas avec une {falha} dans au moins un échantillon ({ic})",
     "von {total} Fällen mit {falha} in mindestens einer Stichprobe ({ic})"),
    ("{casos}: <strong>{a} de {b}</strong> · {respostas}: <strong>{c} de {d}</strong>",
     "{casos}: <strong>{a} of {b}</strong> · {respostas}: <strong>{c} of {d}</strong>",
     "{casos}: <strong>{a} de {b}</strong> · {respostas}: <strong>{c} de {d}</strong>",
     "{casos} : <strong>{a} sur {b}</strong> · {respostas} : <strong>{c} sur {d}</strong>",
     "{casos}: <strong>{a} von {b}</strong> · {respostas}: <strong>{c} von {d}</strong>"),
    ("Casos corretos", "Correct cases", "Casos correctos", "Cas corrects", "Richtige Fälle"),
    ("Respostas corretas", "Correct answers", "Respuestas correctas", "Réponses correctes", "Richtige Antworten"),
    ("{n} de {total} casos", "{n} of {total} cases", "{n} de {total} casos", "{n} sur {total} cas", "{n} von {total} Fällen"),
    ("em {total} casos", "across {total} cases", "en {total} casos", "sur {total} cas", "bei {total} Fällen"),

    # ---- grid, dots
    ("Amostras: {lista}", "Samples: {lista}", "Muestras: {lista}", "Échantillons : {lista}", "Stichproben: {lista}"),
    ("{n} sem resposta", "{n} no answer", "{n} sin respuesta", "{n} sans réponse", "{n} keine Antwort"),
    ("{n} correta", "{n} correct", "{n} correcta", "{n} correct", "{n} richtig"),
    ("{n} incorreta", "{n} incorrect", "{n} incorrecta", "{n} incorrect", "{n} falsch"),
    ("sem resposta", "no answer", "sin respuesta", "sans réponse", "keine Antwort"),
    ("Caso", "Case", "Caso", "Cas", "Fall"),
    ("Casos com falha em pelo menos um modelo. Cada ponto é uma amostra (● correta, ✕ incorreta, ○ sem resposta); por baixo, o tipo de falha mais grave.",
     "Cases with a failure in at least one model. Each dot is a sample (● correct, ✕ incorrect, ○ no answer); below, the most serious failure type.",
     "Casos con fallo en al menos un modelo. Cada punto es una muestra (● correcta, ✕ incorrecta, ○ sin respuesta); debajo, el tipo de fallo más grave.",
     "Cas en échec pour au moins un modèle. Chaque point est un échantillon (● correct, ✕ incorrect, ○ sans réponse) ; en dessous, le type de défaillance le plus grave.",
     "Fälle mit Fehler bei mindestens einem Modell. Jeder Punkt ist eine Stichprobe (● richtig, ✕ falsch, ○ keine Antwort); darunter die schwerwiegendste Fehlerart."),
    ("Nenhum caso com falha.", "No case with a failure.", "Ningún caso con fallo.", "Aucun cas en échec.", "Kein Fall mit Fehler."),
    ("caso sempre correto em todos os modelos", "case always correct in every model", "caso siempre correcto en todos los modelos", "cas toujours correct pour tous les modèles", "Fall bei allen Modellen immer richtig"),
    ("casos sempre corretos em todos os modelos", "cases always correct in every model", "casos siempre correctos en todos los modelos", "cas toujours corrects pour tous les modèles", "Fälle bei allen Modellen immer richtig"),

    # ---- most serious errors, areas
    ("Casos em que todas as amostras falharam, com pelo menos uma falha de risco crítico. Selecionados por regra fixa: os primeiros casos que a cumprem, alternando entre modelos.",
     "Cases in which every sample failed, with at least one critical-risk failure. Selected by a fixed rule: the first cases that meet it, alternating between models.",
     "Casos en los que todas las muestras fallaron, con al menos un fallo de riesgo crítico. Seleccionados por una regla fija: los primeros casos que la cumplen, alternando entre modelos.",
     "Cas dans lesquels tous les échantillons ont échoué, avec au moins une défaillance à risque critique. Sélectionnés selon une règle fixe : les premiers cas qui la remplissent, en alternant entre modèles.",
     "Fälle, in denen alle Stichproben fehlschlugen, mit mindestens einem Fehler mit kritischem Risiko. Nach fester Regel ausgewählt: die ersten Fälle, die sie erfüllen, abwechselnd zwischen den Modellen."),
    ("O modelo respondeu", "The model answered", "El modelo respondió", "Le modèle a répondu", "Das Modell antwortete"),
    ("A referência diz", "The reference says", "La referencia dice", "La référence indique", "Die Referenz sagt"),
    ("Ver o caso completo", "See the full case", "Ver el caso completo", "Voir le cas complet", "Ganzen Fall ansehen"),
    ("Falhas críticas por área clínica", "Critical failures by clinical area", "Fallos críticos por área clínica", "Défaillances critiques par domaine clinique", "Kritische Fehler nach klinischem Bereich"),
    ("Casos com falha crítica em pelo menos uma amostra, por área. Um resultado médio aceitável pode ocultar uma área de risco. A intensidade da cor é proporcional à fração de casos com falha crítica.",
     "Cases with a critical failure in at least one sample, by area. An acceptable average can hide an area of risk. Colour intensity is proportional to the share of cases with a critical failure.",
     "Casos con fallo crítico en al menos una muestra, por área. Un resultado medio aceptable puede ocultar un área de riesgo. La intensidad del color es proporcional a la fracción de casos con fallo crítico.",
     "Cas avec une défaillance critique dans au moins un échantillon, par domaine. Un résultat moyen acceptable peut masquer un domaine à risque. L'intensité de la couleur est proportionnelle à la part de cas avec une défaillance critique.",
     "Fälle mit kritischem Fehler in mindestens einer Stichprobe, nach Bereich. Ein akzeptabler Durchschnitt kann einen Risikobereich verdecken. Die Farbintensität ist proportional zum Anteil der Fälle mit kritischem Fehler."),
    ("Área", "Area", "Área", "Domaine", "Bereich"),
    ("<strong>{a}</strong> de {n}", "<strong>{a}</strong> of {n}", "<strong>{a}</strong> de {n}", "<strong>{a}</strong> sur {n}", "<strong>{a}</strong> von {n}"),

    # ---- case detail
    ("Cada caso apresenta a pergunta, a resposta de referência com a fonte e cada resposta distinta do modelo, com o critério não cumprido e a evidência encontrada pelo corretor. Os círculos à direita indicam o estado do caso em cada modelo, por esta ordem: {modelos}.",
     "Each case shows the question, the reference answer with its source and each distinct answer from the model, with the unmet criterion and the evidence the grader found. The circles on the right show the case's status in each model, in this order: {modelos}.",
     "Cada caso presenta la pregunta, la respuesta de referencia con su fuente y cada respuesta distinta del modelo, con el criterio incumplido y la evidencia encontrada por el corrector. Los círculos de la derecha indican el estado del caso en cada modelo, en este orden: {modelos}.",
     "Chaque cas présente la question, la réponse de référence avec sa source et chaque réponse distincte du modèle, avec le critère non respecté et la preuve relevée par le correcteur. Les cercles à droite indiquent l'état du cas pour chaque modèle, dans cet ordre : {modelos}.",
     "Jeder Fall zeigt die Frage, die Referenzantwort mit Quelle und jede unterschiedliche Antwort des Modells, mit dem nicht erfüllten Kriterium und dem vom Bewerter gefundenen Beleg. Die Kreise rechts zeigen den Status des Falls je Modell, in dieser Reihenfolge: {modelos}."),
    ("Pergunta.", "Question.", "Pregunta.", "Question.", "Frage."),
    ("Resposta de referência.", "Reference answer.", "Respuesta de referencia.", "Réponse de référence.", "Referenzantwort."),
    ("Fonte.", "Source.", "Fuente.", "Source.", "Quelle."),
    ("{a} de {n} amostras corretas", "{a} of {n} samples correct", "{a} de {n} muestras correctas", "{a} sur {n} échantillons corrects", "{a} von {n} Stichproben richtig"),
    ("amostra {n}: cumpre todos os critérios", "sample {n}: meets every criterion", "muestra {n}: cumple todos los criterios", "échantillon {n} : respecte tous les critères", "Stichprobe {n}: erfüllt alle Kriterien"),
    ("amostra {n}", "sample {n}", "muestra {n}", "échantillon {n}", "Stichprobe {n}"),
    ("(corrigida contra: {alternativa})", "(graded against: {alternativa})", "(corregida frente a: {alternativa})", "(corrigée par rapport à : {alternativa})", "(bewertet gegen: {alternativa})"),
    ("Não encontrou nenhum destes termos: ", "None of these terms was found: ", "No encontró ninguno de estos términos: ", "Aucun de ces termes n'a été trouvé : ", "Keiner dieser Begriffe wurde gefunden: "),
    ("Faltou: ", "Missing: ", "Faltó: ", "Manquant : ", "Fehlt: "),
    ("Encontrou o que não devia aparecer: ", "Found what should not appear: ", "Encontró lo que no debía aparecer: ", "A trouvé ce qui ne devait pas apparaître : ", "Gefunden, was nicht vorkommen sollte: "),
    ("Receita o que o caso exclui: ", "Prescribes what the case excludes: ", "Prescribe lo que el caso excluye: ", "Prescrit ce que le cas exclut : ", "Verordnet, was der Fall ausschließt: "),
    ("Não indica nenhum valor em ", "Gives no value in ", "No indica ningún valor en ", "N'indique aucune valeur en ", "Nennt keinen Wert in "),
    ("Esperava ", "Expected ", "Esperaba ", "Attendu : ", "Erwartet: "),
    (" no trecho: ", " in the passage: ", " en el fragmento: ", " dans le passage : ", " in der Passage: "),

    # ---- more indicators
    ("Mais indicadores: falhas por tipo e português europeu", "More indicators: failures by type and European Portuguese", "Más indicadores: fallos por tipo y portugués europeo", "Autres indicateurs : défaillances par type et portugais européen", "Weitere Indikatoren: Fehler nach Art und europäisches Portugiesisch"),
    ("Falhas por tipo", "Failures by type", "Fallos por tipo", "Défaillances par type", "Fehler nach Art"),
    ("Quantas respostas tiveram cada tipo de falha, do risco mais alto para o mais baixo. Uma resposta pode ter mais do que um tipo.",
     "How many answers had each failure type, from highest to lowest risk. An answer can have more than one type.",
     "Cuántas respuestas tuvieron cada tipo de fallo, del riesgo más alto al más bajo. Una respuesta puede tener más de un tipo.",
     "Nombre de réponses présentant chaque type de défaillance, du risque le plus élevé au plus faible. Une réponse peut en présenter plusieurs.",
     "Wie viele Antworten jede Fehlerart aufwiesen, vom höchsten zum niedrigsten Risiko. Eine Antwort kann mehrere Arten haben."),
    ("Nenhuma falha registada.", "No failure recorded.", "Ningún fallo registrado.", "Aucune défaillance enregistrée.", "Kein Fehler erfasst."),
    ("{n} respostas", "{n} answers", "{n} respuestas", "{n} réponses", "{n} Antworten"),
    ("Português europeu", "European Portuguese", "Portugués europeo", "Portugais européen", "Europäisches Portugiesisch"),
    ("Indicador independente, baseado numa lista curta de formas alheias ao português europeu atual. Não entra na contagem de falhas e subestima a frequência real.",
     "A separate indicator, based on a short list of forms foreign to current European Portuguese. It is not part of the failure count and underestimates the true frequency.",
     "Indicador independiente, basado en una lista breve de formas ajenas al portugués europeo actual. No entra en el recuento de fallos y subestima la frecuencia real.",
     "Indicateur distinct, fondé sur une courte liste de formes étrangères au portugais européen actuel. Il n'entre pas dans le décompte des défaillances et sous-estime la fréquence réelle.",
     "Eigener Indikator auf Grundlage einer kurzen Liste von Formen, die dem heutigen europäischen Portugiesisch fremd sind. Er fließt nicht in die Fehlerzählung ein und unterschätzt die tatsächliche Häufigkeit."),
    ("{a} de {n} respostas com formas do português do Brasil, e {b} com grafia anterior ao Acordo Ortográfico.",
     "{a} of {n} answers with Brazilian Portuguese forms, and {b} with spelling from before the Orthographic Agreement.",
     "{a} de {n} respuestas con formas del portugués de Brasil, y {b} con ortografía anterior al Acuerdo Ortográfico.",
     "{a} réponses sur {n} avec des formes du portugais du Brésil, et {b} avec une orthographe antérieure à l'Accord orthographique.",
     "{a} von {n} Antworten mit Formen des brasilianischen Portugiesisch und {b} mit Schreibung vor dem Rechtschreibabkommen."),
    ("Mais frequentes: {lista}.", "Most frequent: {lista}.", "Más frecuentes: {lista}.", "Les plus fréquentes : {lista}.", "Am häufigsten: {lista}."),

    # ---- technical details
    ("Detalhes técnicos: condições do ensaio, glossário e método", "Technical details: test conditions, glossary and method", "Detalles técnicos: condiciones de la prueba, glosario y método", "Détails techniques : conditions de l'essai, glossaire et méthode", "Technische Details: Testbedingungen, Glossar und Methode"),
    ("Condições do ensaio", "Test conditions", "Condiciones de la prueba", "Conditions de l'essai", "Testbedingungen"),
    ("Banco de casos", "Case bank", "Banco de casos", "Banque de cas", "Fallsammlung"),
    ("Sem respostas registadas.", "No answers recorded.", "Sin respuestas registradas.", "Aucune réponse enregistrée.", "Keine Antworten erfasst."),
    ("{n} respostas, recolhidas {periodo}; temperatura {temperatura}; tokens_max {tokens}; versão {versao}",
     "{n} answers, collected {periodo}; temperature {temperatura}; tokens_max {tokens}; version {versao}",
     "{n} respuestas, recogidas {periodo}; temperatura {temperatura}; tokens_max {tokens}; versión {versao}",
     "{n} réponses, recueillies {periodo} ; température {temperatura} ; tokens_max {tokens} ; version {versao}",
     "{n} Antworten, erhoben {periodo}; Temperatur {temperatura}; tokens_max {tokens}; Version {versao}"),
    (" a {fim}", " to {fim}", " a {fim}", " à {fim}", " bis {fim}"),
    ("não registado", "not recorded", "no registrado", "non enregistré", "nicht erfasst"),
    ("não registada", "not recorded", "no registrada", "non enregistrée", "nicht erfasst"),
    ("Glossário", "Glossary", "Glosario", "Glossaire", "Glossar"),
    ("Método", "Method", "Método", "Méthode", "Methode"),
    ("A correção é textual e determinista: cada critério procura termos e valores na resposta, e o mesmo texto dá sempre o mesmo veredicto. O próprio corretor é ensaiado nos dois sentidos: a resposta de referência de cada caso tem de passar, e uma resposta errada construída para cada critério tem de falhar. O modelo nunca vê a resposta de referência nem os critérios.",
     "Grading is textual and deterministic: each criterion looks for terms and values in the answer, and the same text always gets the same verdict. The grader itself is tested both ways: each case's reference answer must pass, and a wrong answer built for each criterion must fail. The model never sees the reference answer or the criteria.",
     "La corrección es textual y determinista: cada criterio busca términos y valores en la respuesta, y el mismo texto recibe siempre el mismo veredicto. El propio corrector se prueba en ambos sentidos: la respuesta de referencia de cada caso debe aprobar, y una respuesta errónea construida para cada criterio debe fallar. El modelo nunca ve la respuesta de referencia ni los criterios.",
     "La correction est textuelle et déterministe : chaque critère recherche des termes et des valeurs dans la réponse, et un même texte reçoit toujours le même verdict. Le correcteur lui-même est testé dans les deux sens : la réponse de référence de chaque cas doit réussir, et une réponse erronée construite pour chaque critère doit échouer. Le modèle ne voit jamais la réponse de référence ni les critères.",
     "Die Bewertung ist textbasiert und deterministisch: Jedes Kriterium sucht Begriffe und Werte in der Antwort, und derselbe Text erhält immer dasselbe Urteil. Der Bewerter selbst wird in beide Richtungen geprüft: Die Referenzantwort jedes Falls muss bestehen, und eine für jedes Kriterium konstruierte falsche Antwort muss scheitern. Das Modell sieht weder die Referenzantwort noch die Kriterien."),
    ("O método completo, os limites conhecidos e a confirmação das fontes estão no repositório do Aferidor, em {metodo} e {verificacao}.",
     "The full method, known limitations and source confirmation are in the Aferidor repository, in {metodo} and {verificacao}.",
     "El método completo, las limitaciones conocidas y la confirmación de las fuentes están en el repositorio del Aferidor, en {metodo} y {verificacao}.",
     "La méthode complète, les limites connues et la confirmation des sources figurent dans le dépôt de l'Aferidor, dans {metodo} et {verificacao}.",
     "Die vollständige Methode, bekannte Grenzen und die Quellenbestätigung stehen im Aferidor-Repository, in {metodo} und {verificacao}."),

    # ---- protocol
    ("Protocolo {nome}, escrito a {data} ({ficheiro}, {sha} {resumo}).", "Protocol {nome}, written on {data} ({ficheiro}, {sha} {resumo}).", "Protocolo {nome}, redactado el {data} ({ficheiro}, {sha} {resumo}).", "Protocole {nome}, rédigé le {data} ({ficheiro}, {sha} {resumo}).", "Protokoll {nome}, verfasst am {data} ({ficheiro}, {sha} {resumo})."),
    ("aprovado", "approved", "aprobado", "approuvé", "freigegeben"),
    ("reprovado", "rejected", "rechazado", "refusé", "abgelehnt"),
    (", não cumpre", ", not met", ", no cumple", ", non respecté", ", nicht erfüllt"),
    ("casos com as {n} amostras", "cases with all {n} samples", "casos con las {n} muestras", "cas avec les {n} échantillons", "Fälle mit allen {n} Stichproben"),
    ("todos os {n}", "all {n}", "los {n}", "les {n}", "alle {n}"),
    ("casos com falha crítica em alguma amostra", "cases with a critical failure in any sample", "casos con fallo crítico en alguna muestra", "cas avec une défaillance critique dans au moins un échantillon", "Fälle mit kritischem Fehler in mindestens einer Stichprobe"),
    ("no máximo {n}", "at most {n}", "como máximo {n}", "au plus {n}", "höchstens {n}"),
    ("casos parcialmente corretos", "partially correct cases", "casos parcialmente correctos", "cas partiellement corrects", "teilweise richtige Fälle"),
    ("taxa de amostras corretas", "rate of correct samples", "tasa de muestras correctas", "taux d'échantillons corrects", "Anteil richtiger Stichproben"),
    ("pelo menos {p}", "at least {p}", "al menos {p}", "au moins {p}", "mindestens {p}"),
    ("o protocolo diz ter sido escrito a {escrito}, depois da primeira resposta ({primeira}): não conta como critério definido antes do ensaio",
     "the protocol says it was written on {escrito}, after the first answer ({primeira}): it does not count as a criterion set before the test",
     "el protocolo dice haber sido redactado el {escrito}, después de la primera respuesta ({primeira}): no cuenta como criterio definido antes de la prueba",
     "le protocole indique avoir été rédigé le {escrito}, après la première réponse ({primeira}) : il ne compte pas comme un critère défini avant l'essai",
     "das Protokoll gibt an, am {escrito} verfasst worden zu sein, nach der ersten Antwort ({primeira}): Es gilt nicht als vor dem Test festgelegtes Kriterium"),
    ("o banco de casos corrido não é o banco para que o protocolo foi escrito (SHA-256 diferente)",
     "the case bank that was run is not the one the protocol was written for (different SHA-256)",
     "el banco de casos ejecutado no es el banco para el que se redactó el protocolo (SHA-256 distinto)",
     "la banque de cas exécutée n'est pas celle pour laquelle le protocole a été rédigé (SHA-256 différent)",
     "die ausgeführte Fallsammlung ist nicht die, für die das Protokoll verfasst wurde (anderer SHA-256)"),
    ("{modelo} correu com {n} amostras por caso; o protocolo previa {previsto}", "{modelo} ran with {n} samples per case; the protocol specified {previsto}", "{modelo} se ejecutó con {n} muestras por caso; el protocolo preveía {previsto}", "{modelo} a été exécuté avec {n} échantillons par cas ; le protocole en prévoyait {previsto}", "{modelo} lief mit {n} Stichproben pro Fall; das Protokoll sah {previsto} vor"),
    ("{modelo} respondeu com a versão {versao}; o protocolo fixou o corretor na versão {previsto}",
     "{modelo} answered with version {versao}; the protocol froze the grader at version {previsto}",
     "{modelo} respondió con la versión {versao}; el protocolo fijó el corrector en la versión {previsto}",
     "{modelo} a répondu avec la version {versao} ; le protocole a figé le correcteur à la version {previsto}",
     "{modelo} antwortete mit Version {versao}; das Protokoll hat den Bewerter auf Version {previsto} festgelegt"),
    ("esta correção foi feita com a versão {versao}; o protocolo fixou o corretor na versão {previsto}: o corretor mudou depois do protocolo",
     "this grading was done with version {versao}; the protocol froze the grader at version {previsto}: the grader changed after the protocol",
     "esta corrección se hizo con la versión {versao}; el protocolo fijó el corrector en la versión {previsto}: el corrector cambió después del protocolo",
     "cette correction a été faite avec la version {versao} ; le protocole a figé le correcteur à la version {previsto} : le correcteur a changé après le protocole",
     "diese Bewertung erfolgte mit Version {versao}; das Protokoll hat den Bewerter auf Version {previsto} festgelegt: der Bewerter wurde nach dem Protokoll geändert"),
    ("{modelo} correu à temperatura {valor}; o protocolo previa {previsto}", "{modelo} ran at temperature {valor}; the protocol specified {previsto}", "{modelo} se ejecutó a temperatura {valor}; el protocolo preveía {previsto}", "{modelo} a été exécuté à la température {valor} ; le protocole prévoyait {previsto}", "{modelo} lief bei Temperatur {valor}; das Protokoll sah {previsto} vor"),

    # ---- model labels
    ("Fornecedor de teste", "Test provider", "Proveedor de prueba", "Fournisseur de test", "Testanbieter"),
    ("respostas fixas, sem modelo real", "fixed answers, no real model", "respuestas fijas, sin modelo real", "réponses fixes, sans modèle réel", "feste Antworten, kein echtes Modell"),
    ("{n} mil milhões de parâmetros", "{n} billion parameters", "{n} mil millones de parámetros", "{n} milliards de paramètres", "{n} Milliarden Parameter"),
    ("executado localmente através do Ollama", "run locally through Ollama", "ejecutado localmente mediante Ollama", "exécuté localement via Ollama", "lokal über Ollama ausgeführt"),
    ("acedido por API", "accessed through an API", "accedido por API", "accessible par API", "per API abgerufen"),

    # ---- states, rules, risks
    ("sempre correto", "always correct", "siempre correcto", "toujours correct", "immer richtig"),
    ("parcialmente correto", "partially correct", "parcialmente correcto", "partiellement correct", "teilweise richtig"),
    ("nunca correto", "never correct", "nunca correcto", "jamais correct", "nie richtig"),
    ("todas as amostras são corretas", "every sample is correct", "todas las muestras son correctas", "tous les échantillons sont corrects", "alle Stichproben richtig sind"),
    ("a maioria das amostras é correta e nenhuma tem falha crítica", "most samples are correct and none has a critical failure", "la mayoría de las muestras es correcta y ninguna tiene fallo crítico", "la majorité des échantillons est correcte et aucun ne présente de défaillance critique", "die meisten Stichproben richtig sind und keine einen kritischen Fehler hat"),
    ("nenhuma amostra tem falha crítica", "no sample has a critical failure", "ninguna muestra tiene fallo crítico", "aucun échantillon ne présente de défaillance critique", "keine Stichprobe einen kritischen Fehler hat"),
    ("risco crítico", "critical risk", "riesgo crítico", "risque critique", "kritisches Risiko"),
    ("risco alto", "high risk", "riesgo alto", "risque élevé", "hohes Risiko"),
    ("risco médio", "medium risk", "riesgo medio", "risque moyen", "mittleres Risiko"),
    ("risco baixo", "low risk", "riesgo bajo", "risque faible", "niedriges Risiko"),
    ("Dose incorreta", "Incorrect dose", "Dosis incorrecta", "Dose incorrecte", "Falsche Dosis"),
    ("Interação omitida", "Interaction omitted", "Interacción omitida", "Interaction omise", "Wechselwirkung ausgelassen"),
    ("Contraindicação omitida", "Contraindication omitted", "Contraindicación omitida", "Contre-indication omise", "Kontraindikation ausgelassen"),
    ("Facto ou fonte inventados", "Invented fact or source", "Hecho o fuente inventados", "Fait ou source inventé", "Erfundene Tatsache oder Quelle"),
    ("Encaminhamento urgente omitido", "Urgent referral omitted", "Derivación urgente omitida", "Orientation urgente omise", "Dringende Überweisung ausgelassen"),
    ("Ajuste de dose omitido", "Dose adjustment omitted", "Ajuste de dosis omitido", "Ajustement de dose omis", "Dosisanpassung ausgelassen"),
    ("Resposta incompleta", "Incomplete answer", "Respuesta incompleta", "Réponse incomplète", "Unvollständige Antwort"),
    ("Recusa indevida", "Unwarranted refusal", "Negativa indebida", "Refus injustifié", "Unberechtigte Ablehnung"),
    ("Formato inválido", "Invalid format", "Formato no válido", "Format non valide", "Ungültiges Format"),

    # ---- categories and case codes
    ("Dose", "Dose", "Dosis", "Dose", "Dosis"),
    ("Diabetes", "Diabetes", "Diabetes", "Diabète", "Diabetes"),
    ("Alergia", "Allergy", "Alergia", "Allergie", "Allergie"),
    ("Duração do tratamento", "Treatment duration", "Duración del tratamiento", "Durée du traitement", "Behandlungsdauer"),
    ("Esquema de tratamento", "Treatment regimen", "Pauta de tratamiento", "Schéma thérapeutique", "Behandlungsschema"),
    ("Critério de tratamento", "Treatment criterion", "Criterio de tratamiento", "Critère de traitement", "Behandlungskriterium"),
    ("Pediatria", "Paediatrics", "Pediatría", "Pédiatrie", "Pädiatrie"),
    ("Interações", "Interactions", "Interacciones", "Interactions", "Wechselwirkungen"),
    ("Formato pedido", "Requested format", "Formato solicitado", "Format demandé", "Verlangtes Format"),
    ("Ajuste de dose", "Dose adjustment", "Ajuste de dosis", "Ajustement de dose", "Dosisanpassung"),
    ("Gravidez", "Pregnancy", "Embarazo", "Grossesse", "Schwangerschaft"),
    ("caso n.º {n}", "case no. {n}", "caso n.º {n}", "cas n° {n}", "Fall Nr. {n}"),
    ("Antibioterapia", "Antibiotic therapy", "Antibioterapia", "Antibiothérapie", "Antibiotikatherapie"),
    ("Interação medicamentosa", "Drug interaction", "Interacción farmacológica", "Interaction médicamenteuse", "Arzneimittelwechselwirkung"),
    ("Formato de resposta imposto", "Required answer format", "Formato de respuesta impuesto", "Format de réponse imposé", "Vorgegebenes Antwortformat"),
    ("Adulto", "Adult", "Adulto", "Adulte", "Erwachsene"),
    ("Cessação tabágica", "Smoking cessation", "Deshabituación tabáquica", "Sevrage tabagique", "Rauchentwöhnung"),
    ("Pneumonia adquirida na comunidade", "Community-acquired pneumonia", "Neumonía adquirida en la comunidad", "Pneumonie communautaire", "Ambulant erworbene Pneumonie"),
    ("Doença pulmonar obstrutiva crónica", "Chronic obstructive pulmonary disease", "Enfermedad pulmonar obstructiva crónica", "Bronchopneumopathie chronique obstructive", "Chronisch obstruktive Lungenerkrankung"),
    ("Cistite", "Cystitis", "Cistitis", "Cystite", "Zystitis"),
    ("Faringite", "Pharyngitis", "Faringitis", "Pharyngite", "Pharyngitis"),
    ("Pielonefrite", "Pyelonephritis", "Pielonefritis", "Pyélonéphrite", "Pyelonephritis"),
    ("Dexametasona", "Dexamethasone", "Dexametasona", "Dexaméthasone", "Dexamethason"),
    ("Tocilizumab", "Tocilizumab", "Tocilizumab", "Tocilizumab", "Tocilizumab"),
    ("Janela para iniciar o antivírico", "Window to start the antiviral", "Ventana para iniciar el antiviral", "Délai pour débuter l'antiviral", "Zeitfenster für den Beginn des Virostatikums"),
    ("Claritromicina", "Clarithromycin", "Claritromicina", "Clarithromycine", "Clarithromycin"),
    ("Colquicina", "Colchicine", "Colchicina", "Colchicine", "Colchicin"),
    ("Metformina", "Metformin", "Metformina", "Metformine", "Metformin"),
    ("Otite média aguda", "Acute otitis media", "Otitis media aguda", "Otite moyenne aiguë", "Akute Otitis media"),
    ("Inibidor da enzima de conversão da angiotensina", "Angiotensin-converting enzyme inhibitor", "Inhibidor de la enzima convertidora de angiotensina", "Inhibiteur de l'enzyme de conversion de l'angiotensine", "ACE-Hemmer"),
    ("Valproato", "Valproate", "Valproato", "Valproate", "Valproat"),
    ("Apixabano", "Apixaban", "Apixabán", "Apixaban", "Apixaban"),
    ("Metotrexato", "Methotrexate", "Metotrexato", "Méthotrexate", "Methotrexat"),
    ("Hipertensão arterial", "Hypertension", "Hipertensión arterial", "Hypertension artérielle", "Arterielle Hypertonie"),
    ("Risco cardiovascular", "Cardiovascular risk", "Riesgo cardiovascular", "Risque cardiovasculaire", "Kardiovaskuläres Risiko"),
    ("Acidente vascular cerebral", "Stroke", "Accidente cerebrovascular", "Accident vasculaire cérébral", "Schlaganfall"),
    ("Fibrilhação auricular", "Atrial fibrillation", "Fibrilación auricular", "Fibrillation auriculaire", "Vorhofflimmern"),

    # ---- glossary terms shown in the page's language
    ("IC 95%", "95% CI", "IC 95 %", "IC 95 %", "95-%-KI"),
    ("parâmetros", "parameters", "parámetros", "paramètres", "Parameter"),
    ("Acordo Ortográfico", "Orthographic Agreement", "Acuerdo Ortográfico", "Accord orthographique", "Rechtschreibabkommen"),
    ("amostra", "sample", "muestra", "échantillon", "Stichprobe"),
    ("falha crítica", "critical failure", "fallo crítico", "défaillance critique", "kritischer Fehler"),
    ("respostas corretas", "correct answers", "respuestas correctas", "réponses correctes", "richtige Antworten"),
    ("casos corretos", "correct cases", "casos correctos", "cas corrects", "richtige Fälle"),
    ("Código do caso", "Case code", "Código del caso", "Code du cas", "Fallcode"),

    # ---- glossary definitions
    ("Direção-Geral da Saúde. Publica as normas de orientação clínica em Portugal.", "Directorate-General of Health, Portugal. Publishes the national clinical guidelines.", "Dirección General de Salud de Portugal. Publica las normas de orientación clínica del país.", "Direction générale de la santé du Portugal. Publie les normes d'orientation clinique nationales.", "Generaldirektion für Gesundheit Portugals. Veröffentlicht die nationalen klinischen Leitlinien."),
    ("Autoridade Nacional do Medicamento e Produtos de Saúde.", "Portuguese National Authority of Medicines and Health Products.", "Autoridad Nacional del Medicamento y Productos Sanitarios de Portugal.", "Autorité nationale portugaise du médicament et des produits de santé.", "Nationale Behörde für Arzneimittel und Gesundheitsprodukte Portugals."),
    ("Resumo das Características do Medicamento: o documento oficial de cada medicamento, com doses, contraindicações e interações.", "Summary of Product Characteristics: the official document for each medicine, with doses, contraindications and interactions.", "Ficha técnica del medicamento: el documento oficial de cada medicamento, con dosis, contraindicaciones e interacciones.", "Résumé des caractéristiques du produit : le document officiel de chaque médicament, avec doses, contre-indications et interactions.", "Fachinformation: das offizielle Dokument jedes Arzneimittels, mit Dosierungen, Kontraindikationen und Wechselwirkungen."),
    ("Associação Portuguesa de Medicina Geral e Familiar, autora do Guia de Bolso de Antibioterapia em Ambulatório.", "Portuguese Association of General and Family Medicine, author of the pocket guide to outpatient antibiotic therapy.", "Asociación Portuguesa de Medicina General y Familiar, autora de la guía de bolsillo de antibioterapia ambulatoria.", "Association portugaise de médecine générale et familiale, auteure du guide de poche d'antibiothérapie ambulatoire.", "Portugiesische Gesellschaft für Allgemein- und Familienmedizin, Herausgeberin des Taschenleitfadens zur ambulanten Antibiotikatherapie."),
    ("Agência Europeia de Medicamentos.", "European Medicines Agency.", "Agencia Europea de Medicamentos.", "Agence européenne des médicaments.", "Europäische Arzneimittel-Agentur."),
    ("Agência do medicamento dos Estados Unidos.", "United States medicines agency (Food and Drug Administration).", "Agencia del medicamento de Estados Unidos.", "Agence du médicament des États-Unis.", "Arzneimittelbehörde der Vereinigten Staaten."),
    ("Sociedade Europeia de Cardiologia, autora de diretrizes clínicas.", "European Society of Cardiology, author of clinical guidelines.", "Sociedad Europea de Cardiología, autora de guías clínicas.", "Société européenne de cardiologie, auteure de recommandations cliniques.", "Europäische Gesellschaft für Kardiologie, Herausgeberin klinischer Leitlinien."),
    ("Associação Americana de Diabetes, autora dos Standards of Care.", "American Diabetes Association, author of the Standards of Care.", "Asociación Americana de Diabetes, autora de los Standards of Care.", "Association américaine du diabète, auteure des Standards of Care.", "Amerikanische Diabetes-Gesellschaft, Herausgeberin der Standards of Care."),
    ("Instituto britânico que publica diretrizes clínicas.", "British institute that publishes clinical guidelines.", "Instituto británico que publica guías clínicas.", "Institut britannique qui publie des recommandations cliniques.", "Britisches Institut, das klinische Leitlinien veröffentlicht."),
    ("Serviço Nacional de Saúde.", "Portuguese National Health Service.", "Servicio Nacional de Salud de Portugal.", "Service national de santé portugais.", "Portugiesischer nationaler Gesundheitsdienst."),
    ("Programa Nacional de Vacinação.", "Portuguese National Vaccination Programme.", "Programa Nacional de Vacunación de Portugal.", "Programme national de vaccination portugais.", "Portugiesisches nationales Impfprogramm."),
    ("Doença pulmonar obstrutiva crónica.", "Chronic obstructive pulmonary disease (COPD).", "Enfermedad pulmonar obstructiva crónica (EPOC).", "Bronchopneumopathie chronique obstructive (BPCO).", "Chronisch obstruktive Lungenerkrankung (COPD)."),
    ("Taxa de filtração glomerular: mede a função dos rins.", "Glomerular filtration rate (GFR): measures kidney function.", "Tasa de filtración glomerular (TFG): mide la función renal.", "Débit de filtration glomérulaire (DFG) : mesure la fonction rénale.", "Glomeruläre Filtrationsrate (GFR): misst die Nierenfunktion."),
    ("Acidente vascular cerebral.", "Stroke.", "Accidente cerebrovascular (ictus).", "Accident vasculaire cérébral (AVC).", "Schlaganfall."),
    ("Hemoglobina glicada: reflete a média da glicemia nos últimos dois a três meses.", "Glycated haemoglobin: reflects average blood glucose over the last two to three months.", "Hemoglobina glicada: refleja la glucemia media de los últimos dos a tres meses.", "Hémoglobine glyquée : reflète la glycémie moyenne des deux à trois derniers mois.", "Glykiertes Hämoglobin: spiegelt den mittleren Blutzucker der letzten zwei bis drei Monate wider."),
    ("Medida da coagulação do sangue, usada para ajustar a dose de varfarina.", "Measure of blood clotting, used to adjust the warfarin dose.", "Medida de la coagulación sanguínea, utilizada para ajustar la dosis de warfarina.", "Mesure de la coagulation sanguine, utilisée pour ajuster la dose de warfarine.", "Maß der Blutgerinnung, zur Anpassung der Warfarin-Dosis."),
    ("Inibidor da enzima de conversão da angiotensina: uma classe de anti-hipertensores.", "Angiotensin-converting enzyme (ACE) inhibitor: a class of antihypertensives.", "Inhibidor de la enzima convertidora de angiotensina (IECA): una clase de antihipertensivos.", "Inhibiteur de l'enzyme de conversion (IEC) : une classe d'antihypertenseurs.", "ACE-Hemmer: eine Klasse von Blutdrucksenkern."),
    ("Enzima de conversão da angiotensina.", "Angiotensin-converting enzyme (ACE).", "Enzima convertidora de angiotensina (ECA).", "Enzyme de conversion de l'angiotensine (ECA).", "Angiotensin-konvertierendes Enzym (ACE)."),
    ("Antagonista dos recetores da angiotensina II: uma classe de anti-hipertensores.", "Angiotensin II receptor blocker (ARB): a class of antihypertensives.", "Antagonista de los receptores de angiotensina II (ARA II): una clase de antihipertensivos.", "Antagoniste des récepteurs de l'angiotensine II (ARA II) : une classe d'antihypertenseurs.", "Angiotensin-II-Rezeptorblocker (Sartan): eine Klasse von Blutdrucksenkern."),
    ("Anticoagulante oral direto (apixabano, rivaroxabano, edoxabano, dabigatrano).", "Direct oral anticoagulant (apixaban, rivaroxaban, edoxaban, dabigatran).", "Anticoagulante oral directo (apixabán, rivaroxabán, edoxabán, dabigatrán).", "Anticoagulant oral direct (apixaban, rivaroxaban, édoxaban, dabigatran).", "Direktes orales Antikoagulans (Apixaban, Rivaroxaban, Edoxaban, Dabigatran)."),
    ("Terapêutica de substituição de nicotina: adesivos, pastilhas, gomas ou spray.", "Nicotine replacement therapy: patches, lozenges, gum or spray.", "Terapia sustitutiva de nicotina: parches, comprimidos, chicles o espray.", "Traitement de substitution nicotinique : patchs, pastilles, gommes ou spray.", "Nikotinersatztherapie: Pflaster, Lutschtabletten, Kaugummis oder Spray."),
    ("Inibidores do SGLT2: uma classe de antidiabéticos orais (por exemplo, dapagliflozina).", "SGLT2 inhibitors: a class of oral antidiabetics (for example, dapagliflozin).", "Inhibidores del SGLT2: una clase de antidiabéticos orales (por ejemplo, dapagliflozina).", "Inhibiteurs du SGLT2 : une classe d'antidiabétiques oraux (par exemple, la dapagliflozine).", "SGLT2-Hemmer: eine Klasse oraler Antidiabetika (zum Beispiel Dapagliflozin)."),
    ("Enzima do fígado que elimina muitos medicamentos; bloqueá-la faz subir os níveis de outros.", "Liver enzyme that clears many drugs; blocking it raises the levels of others.", "Enzima hepática que elimina muchos fármacos; bloquearla eleva los niveles de otros.", "Enzyme hépatique qui élimine de nombreux médicaments ; la bloquer augmente les taux d'autres médicaments.", "Leberenzym, das viele Arzneimittel abbaut; seine Hemmung erhöht die Spiegel anderer."),
    ("Monitorização ambulatória da pressão arterial, durante 24 horas.", "Ambulatory blood pressure monitoring over 24 hours.", "Monitorización ambulatoria de la presión arterial durante 24 horas.", "Mesure ambulatoire de la pression artérielle sur 24 heures.", "Ambulante 24-Stunden-Blutdruckmessung."),
    ("Automedição da pressão arterial, no domicílio.", "Home blood pressure self-measurement.", "Automedida de la presión arterial en el domicilio.", "Automesure tensionnelle à domicile.", "Blutdruckselbstmessung zu Hause."),
    ("Tensão arterial.", "Blood pressure.", "Tensión arterial.", "Tension artérielle.", "Blutdruck."),
    ("Via intramuscular.", "Intramuscular route.", "Vía intramuscular.", "Voie intramusculaire.", "Intramuskulär."),
    ("Via intravenosa.", "Intravenous route.", "Vía intravenosa.", "Voie intraveineuse.", "Intravenös."),
    ("Instrumento europeu que estima o risco cardiovascular a 10 anos.", "European tool that estimates 10-year cardiovascular risk.", "Herramienta europea que estima el riesgo cardiovascular a 10 años.", "Outil européen qui estime le risque cardiovasculaire à 10 ans.", "Europäisches Instrument zur Schätzung des kardiovaskulären 10-Jahres-Risikos."),
    ("Versão anterior do SCORE2, usada pela norma da DGS de 2013.", "Earlier version of SCORE2, used by the 2013 DGS guideline.", "Versión anterior de SCORE2, utilizada por la norma de la DGS de 2013.", "Version antérieure de SCORE2, utilisée par la norme de la DGS de 2013.", "Frühere Version von SCORE2, verwendet in der DGS-Leitlinie von 2013."),
    ("Intervalo de confiança a 95%: a faixa onde o valor real provavelmente está. Com poucos casos, é larga.", "95% confidence interval: the range where the true value probably lies. With few cases, it is wide.", "Intervalo de confianza del 95 %: el rango en el que probablemente está el valor real. Con pocos casos, es amplio.", "Intervalle de confiance à 95 % : la plage où se situe probablement la valeur réelle. Avec peu de cas, il est large.", "95-%-Konfidenzintervall: der Bereich, in dem der wahre Wert wahrscheinlich liegt. Bei wenigen Fällen ist er breit."),
    ("Impressão digital de um ficheiro: muda se o ficheiro mudar uma única vírgula. Serve para provar que nada foi alterado.", "A file's fingerprint: it changes if a single comma of the file changes. It proves that nothing was altered.", "Huella digital de un archivo: cambia si cambia una sola coma del archivo. Sirve para demostrar que nada se ha alterado.", "Empreinte d'un fichier : elle change si une seule virgule du fichier change. Elle permet de prouver que rien n'a été modifié.", "Fingerabdruck einer Datei: Er ändert sich, wenn sich auch nur ein Komma ändert. Er belegt, dass nichts verändert wurde."),
    ("Programa que corre modelos de linguagem abertos no próprio computador, sem enviar nada para fora.", "Program that runs open language models on one's own computer, sending nothing outside.", "Programa que ejecuta modelos de lenguaje abiertos en el propio ordenador, sin enviar nada al exterior.", "Programme qui exécute des modèles de langage ouverts sur l'ordinateur même, sans rien envoyer à l'extérieur.", "Programm, das offene Sprachmodelle auf dem eigenen Computer ausführt, ohne etwas nach außen zu senden."),
    ("Medida do tamanho de um modelo de linguagem. Mais parâmetros costuma querer dizer mais capacidade.", "Measure of a language model's size. More parameters usually means more capability.", "Medida del tamaño de un modelo de lenguaje. Más parámetros suele significar más capacidad.", "Mesure de la taille d'un modèle de langage. Davantage de paramètres signifie généralement davantage de capacités.", "Maß für die Größe eines Sprachmodells. Mehr Parameter bedeuten meist mehr Leistungsfähigkeit."),
    ("Limite de tamanho da resposta que o modelo podia dar.", "Limit on the length of the answer the model could give.", "Límite de longitud de la respuesta que el modelo podía dar.", "Limite de longueur de la réponse que le modèle pouvait donner.", "Obergrenze für die Länge der Antwort, die das Modell geben konnte."),
    ("O Acordo Ortográfico de 1990, em vigor em Portugal: escreve-se infeção e não infecção.", "The 1990 Orthographic Agreement, in force in Portugal: \"infeção\" is written, not \"infecção\".", "El Acuerdo Ortográfico de 1990, vigente en Portugal: se escribe \"infeção\" y no \"infecção\".", "L'Accord orthographique de 1990, en vigueur au Portugal : on écrit « infeção » et non « infecção ».", "Das Rechtschreibabkommen von 1990, in Portugal gültig: Man schreibt „infeção“, nicht „infecção“."),
    ("Uma das respostas do modelo à mesma pergunta. Cada caso é perguntado várias vezes, porque o modelo não responde sempre igual.", "One of the model's answers to the same question. Each case is asked several times, because the model does not always answer the same way.", "Una de las respuestas del modelo a la misma pregunta. Cada caso se formula varias veces, porque el modelo no responde siempre igual.", "L'une des réponses du modèle à la même question. Chaque cas est posé plusieurs fois, car le modèle ne répond pas toujours de la même façon.", "Eine der Antworten des Modells auf dieselbe Frage. Jeder Fall wird mehrmals gestellt, weil das Modell nicht immer gleich antwortet."),
    ("Todas as amostras do caso cumpriram todos os critérios.", "Every sample of the case met every criterion.", "Todas las muestras del caso cumplieron todos los criterios.", "Tous les échantillons du cas ont respecté tous les critères.", "Alle Stichproben des Falls erfüllten alle Kriterien."),
    ("Parte das amostras cumpriu os critérios e parte não: o resultado dependeu da tentativa.", "Some samples met the criteria and some did not: the result depended on the attempt.", "Parte de las muestras cumplió los criterios y parte no: el resultado dependió del intento.", "Une partie des échantillons a respecté les critères et une autre non : le résultat a dépendu de la tentative.", "Ein Teil der Stichproben erfüllte die Kriterien, ein Teil nicht: Das Ergebnis hing vom Versuch ab."),
    ("Nenhuma amostra cumpriu os critérios. Não implica falha crítica: a falha pode ser apenas uma resposta incompleta.", "No sample met the criteria. This does not imply a critical failure: the failure may be only an incomplete answer.", "Ninguna muestra cumplió los criterios. No implica un fallo crítico: el fallo puede ser solo una respuesta incompleta.", "Aucun échantillon n'a respecté les critères. Cela n'implique pas de défaillance critique : il peut s'agir seulement d'une réponse incomplète.", "Keine Stichprobe erfüllte die Kriterien. Das bedeutet keinen kritischen Fehler: Es kann sich nur um eine unvollständige Antwort handeln."),
    ("Erro de dose, interação ou contraindicação omitida, encaminhamento urgente omitido, ou facto inventado.", "Dose error, omitted interaction or contraindication, omitted urgent referral, or invented fact.", "Error de dosis, interacción o contraindicación omitida, derivación urgente omitida o hecho inventado.", "Erreur de dose, interaction ou contre-indication omise, orientation urgente omise ou fait inventé.", "Dosisfehler, ausgelassene Wechselwirkung oder Kontraindikation, ausgelassene dringende Überweisung oder erfundene Tatsache."),
    ("Contagem de respostas (casos × amostras), não de casos. Uma taxa alta pode ocultar casos nunca corretos.", "A count of answers (cases × samples), not of cases. A high rate can hide never-correct cases.", "Recuento de respuestas (casos × muestras), no de casos. Una tasa alta puede ocultar casos nunca correctos.", "Décompte de réponses (cas × échantillons), et non de cas. Un taux élevé peut masquer des cas jamais corrects.", "Zählung von Antworten (Fälle × Stichproben), nicht von Fällen. Eine hohe Rate kann nie richtige Fälle verdecken."),
    ("Veredicto binário por caso, segundo a regra indicada no relatório. Por omissão, um caso é correto apenas se todas as amostras forem corretas.", "A yes-or-no verdict per case, under the rule stated in the report. By default, a case is correct only if every sample is correct.", "Veredicto binario por caso, según la regla indicada en el informe. Por defecto, un caso es correcto solo si todas las muestras son correctas.", "Verdict binaire par cas, selon la règle indiquée dans le rapport. Par défaut, un cas n'est correct que si tous les échantillons sont corrects.", "Binäres Urteil je Fall nach der im Bericht angegebenen Regel. Standardmäßig ist ein Fall nur richtig, wenn alle Stichproben richtig sind."),
    ("Cada caso tem um código com a área, o tema e o número: ATB-PAC-001 é antibioterapia, pneumonia adquirida na comunidade, caso n.º 1. Passe o rato por cima de um código para o ler.", "Each case has a code with the area, the topic and the number: ATB-PAC-001 is antibiotic therapy, community-acquired pneumonia, case no. 1. Hover over a code to read it.", "Cada caso tiene un código con el área, el tema y el número: ATB-PAC-001 es antibioterapia, neumonía adquirida en la comunidad, caso n.º 1. Pase el ratón por encima de un código para leerlo.", "Chaque cas a un code indiquant le domaine, le thème et le numéro : ATB-PAC-001 correspond à antibiothérapie, pneumonie communautaire, cas n° 1. Survolez un code pour le lire.", "Jeder Fall hat einen Code aus Bereich, Thema und Nummer: ATB-PAC-001 steht für Antibiotikatherapie, ambulant erworbene Pneumonie, Fall Nr. 1. Fahren Sie mit der Maus über einen Code, um ihn zu lesen."),
)

CATALOG: dict[str, dict[str, str]] = {
    pt: {"en": en, "es": es, "fr": fr, "de": de} for pt, en, es, fr, de in _ROWS
}
CATALOG.update({s: {"en": s, "es": s, "fr": s, "de": s} for s in _SAME})
